export enum IpcEvents {
  OPEN_SETTINGS = 'OPEN_SETTINGS',
  OPEN_GAME_VIEW = 'OPEN_GAME_VIEW',
  CLOSE_GAME_VIEW = 'CLOSE_GAME_VIEW',
  START_HTTP_SERVER = 'START_HTTP_SERVER',
  LOAD_GAME_MAINJS = 'LOAD_GAME_MAINJS',
  DOWNLOAD_GAME_DEMO = 'DOWNLOAD_GAME_DEMO',
  READ_GAMESPACE_DIRS = 'READ_GAMESPACE_DIRS',
  OPEN_GMSPACE_DIRS = 'OPEN_GMSPACE_DIRS',
  CHECK_DIR_EXISTS = 'CHECK_DIR_EXISTS',
  DOWNLOAD_GAME_TEMPLATE = 'DOWNLOAD_GAME_TEMPLATE',
  // more ...
}

export const ipcMainEvents = [];
export const ipcRendererEvents = [];
export const WEBCONTENTS_READY_FOR_IPC_SIGNAL =
  'WEBCONTENTS_READY_FOR_IPC_SIGNAL';
