export enum IpcEvents {
  OPEN_FILE_FROM_DIALOG = 'OPEN_FILE_FROM_DIALOG',
  OPEN_SETTINGS = 'OPEN_SETTINGS',
  OPEN_GAME_VIEW = 'OPEN_GAME_VIEW',
  OPEN_EXTERNAL_URL = 'OPEN_EXTERNAL_URL',
  CLOSE_GAME_VIEW = 'CLOSE_GAME_VIEW',
  START_HTTP_SERVER = 'START_HTTP_SERVER',
  LOAD_GAME_MAINJS = 'LOAD_GAME_MAINJS',
  DOWNLOAD_GAME_DEMO = 'DOWNLOAD_GAME_DEMO',
  READ_GAMESPACE_DIRS = 'READ_GAMESPACE_DIRS',
  OPEN_GMSPACE_DIRS = 'OPEN_GMSPACE_DIRS',
  CHECK_DIR_EXISTS = 'CHECK_DIR_EXISTS',
  DOWNLOAD_GAME_TEMPLATE = 'DOWNLOAD_GAME_TEMPLATE',
  DELETE_GAME_FOLDER = 'DELETE_GAME_FOLDER',
  SAVE_GAME_FILE = 'SAVE_GAME_FILE',
  SAVE_MAP_FILE = 'SAVE_MAP_FILE',
  EXPORT_MAP_FILE = 'EXPORT_MAP_FILE',
  TOGGLE_DEV_TOOLS = 'TOGGLE_DEV_TOOLS',
  READ_IMAGE_FILE = 'READ_IMAGE_FILE',
  READ_PNG_IMAGE = 'READ_PNG_IMAGE',
  READ_MAP_FILE = 'READ_MAP_FILE',
  FETCH_REMOTE_JSON = 'FETCH_REMOTE_JSON',
  FETCH_REMOTE_TEXT = 'FETCH_REMOTE_TEXT',
  DOWNLOAD_TILESHEETTS = 'DOWNLOAD_TILESHEETTS',
  // more ...
}

export const ipcMainEvents = [];
export const ipcRendererEvents = [];
export const WEBCONTENTS_READY_FOR_IPC_SIGNAL =
  'WEBCONTENTS_READY_FOR_IPC_SIGNAL';
